# Path to sources
#sonar.sources=.
#sonar.exclusions=
#sonar.inclusions=
sonar.sources=CW1
sonar.exclusions=CW1/node_modules/**,CW1/tests/**

# Path to tests
#sonar.tests=
#sonar.test.exclusions=
#sonar.test.inclusions=
sonar.tests=CW1/tests
sonar.test.inclusions=CW1/tests/**

# Source encoding
#sonar.sourceEncoding=UTF-8
sonar.sourceEncoding=UTF-8

# Exclusions for copy-paste detection
#sonar.cpd.exclusions=
