# Path to sources
#sonar.sources=.
#sonar.exclusions=
#sonar.inclusions=
sonar.sources=alum
sonar.exclusions=alum/node_modules/**,alum/tests/**

# Path to tests
#sonar.tests=
#sonar.test.exclusions=
#sonar.test.inclusions=
sonar.tests=alum/tests
sonar.test.inclusions=alum/tests/**

# Source encoding
#sonar.sourceEncoding=UTF-8
sonar.sourceEncoding=UTF-8

# Exclusions for copy-paste detection
#sonar.cpd.exclusions=
